name = "mezcalomano-shop"
compatibility_date = "2026-01-14"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "mezcalomano-shop"
database_id = "058e2faf-6a00-403f-b8ad-1b545e5e1fe4"

[[kv_namespaces]]
binding = "KV"
id = "e553a34b629d4a3cbd34be6845c9bb72"
